### ISSUE TITLE
A few issues - Backup Upload

### ISSUE THREAD

**Issue by Clanwarz** [Alexr03/TCAdminBackup#2]
Alex,

I have a video of a server error I would like for you to see, but it's not meant foir public view.

**Comment by Alexr03** [comment]
Email it to me alex@alexr03.dev

**Comment by Alexr03** [comment]
@Clanwarz Hi Jay, That extra semi-colon was removed in a recent update, can you update to the latest version?

Also, login to the machine that is hosting the control panel and login to http://localhost then try to backup a service, it will tell you the real error, that I need in order to help you.

As for batch updates, can you goto https://admin.clanwarz.com/SteamUpdate ?

**Comment by Alexr03** [comment]
@Clanwarz Has this been sorted?

**Comment by Clanwarz** [comment]
These items have been sorted and are now working properly:
1. Right-Click Compress
2. Right-Click Backup ( FTP )
3. Restore From Backup ( FTP )

Navigating to SteamUpdate still brings me to ```?unassignedpage=SteamUpdate/Index```

I have noticed a strange date/version declaration in my install. 
![install-date](https://user-images.githubusercontent.com/3459495/88445669-b9699580-cde9-11ea-9a75-32913acc8c72.png)

Should I uninstall and install which version?

As a side note, a button to choose all files/folders would benefit and minimize steps while doing a manual backup.

Appreciate the help.

**Comment by Alexr03** [comment]
Good to hear!
I'm unsure why the date is inconsistent, we are simply relaying the data we get from Invisions API.

Install 1.0.4 of **Batch Steam Update** I have made a change that should fix it for you.

**Comment by Clanwarz** [comment]
Right on. That worked. Do you have any plans on extented the functionaly to admin?
- Udate All of Your Steam Game Servers
- Update All Reseller Steam Game Servers

**Comment by Alexr03** [comment]
TCAdmin has a way to recursively check the servers you have access to rather than ones you own. But if you are an Admin and it starts showing hundreds if not thousands of servers, i'm not sure how the page will handle it. 🤣

Create an issue on the batch steam update git repository and i'll take a look into it when I get the chance, currently working on another module.

**Comment by Clanwarz** [comment]
Alex, one last thing. The left menu , "Batch Steam Update" exists for 
all clients, with or without a Steam game.

------ Original Message ------

**Comment by Alexr03** [comment]
Update to 1.0.5

**Comment by Alexr03** [comment]
Will be closing now. Create another issue for anything else, cheers.
